### ISSUE TITLE
CDN Version

### ISSUE THREAD

**Issue by josuemartinezz** [codeforms/Punica-CSS-Framework#2]
Please upload the cdn version 👀🤑

**Comment by UnderlineWords** [comment]
Added CDN links to documentation. (https://github.com/codeforms/Punica-CSS-Framework/commit/9e0e6a6a4eb8d28a823562a5e31cb8a6e66a9568)

Copy paste to your project;
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/codeforms/Punica-CSS-Framework/dist/punica.min.css" crossorigin="anonymous">

```
